version: 0.0
Resources:
  - demo-serverless-lambda:
      Type: AWS::Lambda::Function
      Properties:
        Name: "demo-serverless-lambda"
#        Alias: "default"
 #       CurrentVersion: "$LATEST"
  #      TargetVersion: "$LATEST"
#Hooks:
 # - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  #- AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
